[package]
name = "orco-cranelift"
version = "0.1.0"
edition = "2021"

[dependencies]
orco = { workspace = true }
log = { workspace = true }

cranelift = "0.113.1"
cranelift-object = "0.113.1"
cranelift-module = "0.113.1"
