[package]
name = "orco-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.4.18"
rayon = "1.8.1"

orco = { path = "../orco" }
orco-rust = { path = "../orco-rust" }
orco-lang = { path = "../orco-lang" }
