[package]
name = "orco-rustc"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[package.metadata.rust-analyzer]
rustc_private = true

[dependencies]
orco = { workspace = true }
orco-cgen = { workspace = true }
